
version: "3"
services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=foodb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234